services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    image: my-image:latest # Replace with your Node.js Docker image
    container_name: web
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://myuser:mypassword@postgres_db:5432/mydatabase
    depends_on:
      - postgres 
volumes:
  pgdata:
